// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkzxhSQ71Ni-VQBy3iidZAi445dG10h0o',
    appId: '1:317727880913:web:d7cee76bc270ab928ef7f0',
    messagingSenderId: '317727880913',
    projectId: 'dppb-tubes',
    authDomain: 'dppb-tubes.firebaseapp.com',
    storageBucket: 'dppb-tubes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmTPeFHyPi7DDMCmRA5Prf8UuGVGhJTmM',
    appId: '1:317727880913:android:a076b42e512afcb18ef7f0',
    messagingSenderId: '317727880913',
    projectId: 'dppb-tubes',
    storageBucket: 'dppb-tubes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxTxDnBFe-Q2U3cvu_1dTN2StnfFTnn3Q',
    appId: '1:317727880913:ios:867d8762412000288ef7f0',
    messagingSenderId: '317727880913',
    projectId: 'dppb-tubes',
    storageBucket: 'dppb-tubes.appspot.com',
    iosClientId: '317727880913-cpkmoe6n3b54kl6h8dumjmhkvh7p8gid.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMenuMakanan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxTxDnBFe-Q2U3cvu_1dTN2StnfFTnn3Q',
    appId: '1:317727880913:ios:867d8762412000288ef7f0',
    messagingSenderId: '317727880913',
    projectId: 'dppb-tubes',
    storageBucket: 'dppb-tubes.appspot.com',
    iosClientId: '317727880913-cpkmoe6n3b54kl6h8dumjmhkvh7p8gid.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMenuMakanan',
  );
}
